name: Build and Package Leinad Spoofer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore Solution
      run: msbuild "Leinad Spoofer.sln" /t:Restore /p:Configuration=Release

    - name: Build Solution
      run: msbuild "Leinad Spoofer.sln" /p:Configuration=Release

    - name: Create Developer Package
      run: msbuild "Leinad Spoofer.Package/Leinad Spoofer.Package.wapproj" /p:Configuration=Release /p:UapAppxPackageBuildMode=Developer /p:AppxBundle=Never

    - name: Upload Package Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Leinad Spoofer MSIX Package
        path: Leinad\ Spoofer.Package/AppPackages
